# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6a42f18eb42a0da4a9e0ce7fdbc369a6807d09efe71e31757d04a502c61042a13696fc952ac2c72b217f28d07601cffac0c1b1a82525682a0e8e5ef71237101

test:
  secret_key_base: 03bb4807d2dc3725cdc3889f3958d19b714db5b6e138bb91e7c713de398b565ae1e070be53c0f6caa3f779274d1c591bbac560850c6c8104cb55c957a3c7067c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
